In [7]:
import re
import docx2txt
import os
import pandas as pd

In [37]:
# docx_path = "cashier.txt"



def list_files_in_folder(folder_path):
    # Get a list of all files in the folder
    files = os.listdir(folder_path)

    # Filter out directories and create a list of file names with extensions
    file_names_with_extensions = [file for file in files if os.path.isfile(os.path.join(folder_path, file))]

    return file_names_with_extensions

def extract_text_from_docx(docx_path):
    txt = docx2txt.process(docx_path)
    if txt:
        return txt.replace('\t', ' ')
    return None


def extract_information(text):
    # Define regex patterns
    name_pattern = re.compile(r'\b([A-Z][a-z]+ [A-Z][a-z]+)\b')
    email_pattern = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b')
    phone_number_pattern = re.compile(r'[\+\(]?[1-9][0-9 .\-\(\)]{8,}[0-9]')
    address_pattern = re.compile(r'\b\d{1,5}[^a-zA-Z0-9]*[a-zA-Z0-9\s,.#]+\b')

    # Extract information
    name_match = name_pattern.findall(text)
    email_match = email_pattern.search(text)
    phone_number_match = phone_number_pattern.findall(text)
    address_match = address_pattern.findall(text)

    # Retrieve matched groups or return None if not found
    name = name_match if name_match else None
    email = email_match.group() if email_match else None
    phone_number = phone_number_match if phone_number_match else None
    address = address_match if address_match else None
        


    return name, email, phone_number,address

def append_row_to_dataframe(df, name,email,phone,address):
    new_row = {"Name": name,"Email":email ,"Phone_number": phone,'Address': address}
    df.loc[len(df)]= new_row
    return df

def filter_address(address):
    pattern = re.compile('\b\d{1,5}\s+[a-zA-Z0-9\s,.#]+\b')
    matched = pattern.search(address)

In [38]:
to_be_extracted = list_files_in_folder("docx/")
df = pd.DataFrame(columns=['Name','Email','Phone_number','Address'])
for file in to_be_extracted:
    txt = extract_text_from_docx(f"docx/{file}")
    extracted_name,extracted_email,extracted_phone,extracted_address = extract_information(txt)
    df= append_row_to_dataframe(df,extracted_name,extracted_email,extracted_phone,extracted_address)

In [39]:
df

,Name,Email,Phone_number,Address
0,"[Christine Smith, Christine Smith, New York, N...",christine.smith@mail.com,"[+1 (970) 333-3833, +1 (970) 333-3833]","[344 ELM STREET MADISON, SD 57042, 1 (970, 333..."
1,"[Software Engineer, Skill Highlights, Software...",matthew.eliot@Mail.com,[+1 (970) 333-3833],"[344 ELM STREET MADISON, SD 57042, 1 (970, 333..."
2,"[Senior Web, Skill Highlights, Web Developer, ...",matthew.eliot@mail.com,"[+1 (970) 333-3833, +1 (970) 333-3833]","[09/2015 to 05, 2019\n\nLuna Web Design, New Y..."
3,"[Qualified Customer, Service Representative, I...",CHRISTINE.SMIDTH@MAIL.COM,"[+1 (970) 333-3833, +1 (970) 333-3833]","[4 years in fast, 4 years in fast, 04/2017 to ..."

In [32]:
df

,Name,Email,Phone_number,Address
0,Christine Smith,christine.smith@mail.com,"[+1 (970) 333-3833, +1 (970) 333-3833]","[344 ELM STREET MADISON, SD 57042, 1 (970, 333..."
1,Software Engineer,matthew.eliot@Mail.com,[+1 (970) 333-3833],"[344 ELM STREET MADISON, SD 57042, 1 (970, 333..."
2,Senior Web,matthew.eliot@mail.com,"[+1 (970) 333-3833, +1 (970) 333-3833]","[09/2015 to 05, 2019\n\nLuna Web Design, New Y..."
3,Qualified Customer,CHRISTINE.SMIDTH@MAIL.COM,"[+1 (970) 333-3833, +1 (970) 333-3833]","[4 years in fast, 4 years in fast, 04/2017 to ..."

In [47]:
txt = extract_text_from_docx(f"docx/sample.docx")
print(txt)
name,email,phone,address = extract_information('docx/soft.docx')

Summary

Senior Web Developer specializing in front end development. Experienced with all stages of the development cycle for dynamic web projects. Well-versed in numerous programming languages including HTML5, PHP OOP, JavaScript, CSS, MySQL. Strong background in project management and customer relations.

Skill Highlights

Project management

Strong decision maker

Complex problem solver

Creative design

Innovative

Service-focused

Experience

Web Developer - 09/2015 to 05/2019

Luna Web Design, New York

Cooperate with designers to create clean interfaces and simple, intuitive interactions and experiences.

Develop project concepts and maintain optimal workflow.

Work with senior developer to manage large, complex design projects for corporate clients.

Complete detailed programming and development tasks for front end public and internal websites as well as challenging back-end server code.

Carry out quality assurance tests to discover errors and optimize usability.

Education

Bachelor of Science: Computer Information Systems - 2014

Columbia University, NY

Certifications

PHP Framework (certificate): Zend, Codeigniter, Symfony.

Programming Languages: JavaScript, HTML5, PHP OOP, CSS, SQL, MySQL.



Summary

Senior Web Developer specializing in front end development. Experienced with all stages of the development cycle for dynamic web projects. Well-versed in numerous programming languages including HTML5, PHP OOP, JavaScript, CSS, MySQL. Strong background in project management and customer relations.

Skill Highlights

Project management

Strong decision maker

Complex problem solver

Creative design

Innovative

Service-focused

Experience

Web Developer - 09/2015 to 05/2019

Luna Web Design, New York

Cooperate with designers to create clean interfaces and simple, intuitive interactions and experiences.

Develop project concepts and maintain optimal workflow.

Work with senior developer to manage large, complex design projects for corporate clients.

Complete detailed programming and development tasks for front end public and internal websites as well as challenging back-end server code.

Carry out quality assurance tests to discover errors and optimize usability.

Education

Bachelor of Science: Computer Information Systems - 2014

Columbia University, NY

Certifications

PHP Framework (certificate): Zend, Codeigniter, Symfony.

Programming Languages: JavaScript, HTML5, PHP OOP, CSS, SQL, MySQL.



MATTHEW ELIOT

MATTHEW ELIOT

+1 (970) 333-3833

matthew.eliot@mail.com

https://linkedin.com/mattheweliot

+1 (970) 333-3833

matthew.eliot@mail.com

https://linkedin.com/mattheweliot

In [44]:
print(name)

None